import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import './globals.scss';
import Header from '@/components/ui/header/Header';
import Footer from '@/components/ui/footer/Footer';

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900'],  style: ['normal', 'italic'], variable: '--font-roboto' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${roboto.variable}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
